input:
  http_server:
    address: 0.0.0.0:4196
    path: /echo

pipeline:
  processors:
    - sleep:
        duration: 500ms
    - mapping: |
        root.about = "%s ğŸ± is a %s %s".format(this.name.capitalize(), this.features.join(" & "), this.type.split("_").join(" "))
        root.stars = "â˜…".repeat((this.stars / 300))
    - sync_response: {}

output:
  stdout: {}